# With the money I have, which is the best district to invest on? 

You have 10 points to distribute across three variables. Please provide more points to what you give more importance when doing an investment.

- **PER** number of years to get the return of investment.
- **RB** Anual rental return.
- **revaluation** Increase in property value. The apartment price after the PER years therefore the original investment is recovered.

## Code

In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler


pd.set_option('display.float_format', '{:.3f}'.format)


def calculate_investment_score(data, input_money, weight_revaluation, weight_rent_anual, weight_per):
    try:
        data['loan'] = data['sell'].apply(lambda x: x - float(input_money)) # keep just the ones with 0 or positive loan
        filtered = data[data['loan'] > 0].copy()
        scaler = MinMaxScaler()
        filtered['normalized_loan'] = scaler.fit_transform(1 / filtered[['loan']])
        filtered['score'] = (
                            float(weight_rent_anual)/10 * filtered['norm_RB']
                             + float(weight_revaluation)/10 * filtered['norm_revaluation']
                             + float(weight_per)/10 * filtered['norm_PER']
                            )
        cols = ['distrito', 'size_rent', 'size_sell', 'mean_meters', 'rent', 'sell', 'RB', 'PER', 'score', 'revaluation', 'loan', 'advertised_rent', 'advertised_sell']
        filtered = filtered[cols]
        filtered = filtered.sort_values(by=['loan'])
    except Exception:
        print('Please enter valid numbers')
    return filtered


data = pd.read_csv('../data/info_per_district_and_meters.csv')

Columns information:

- advertised_rent: the average advertised time of the apartments for renting in this group is 1.244643 months
- advertised_sell: the average advertised time of the apartments for sale in this group is 2.062019 months
- size_rent: number of apartments for renting with these characteristics
- size_sell: number of apartments for sale with these characteristics
- €/meter_rent: Average renting price per square meter 
- €/meter_sell: Average selling price per square meter 
- apartments: total number of apartments, in alcala-de-henares. This value can be used to calculate the percentage of apartments for sale and for rent from each district
- RB: annual rental yield compared to the purchase price. Formula: RB = ((€/meter_rent*12) / €/meter_sell) * 100
- PER (Price-to-Earnings): number of years to recover the sale price with the rent. Formula PER = €/meter_sell / (€/meter_rent*12)
- change_2014_2024_sell: average change rate in sale price from 2014 to 2024
- change_2014_2024_rent: average change rate in renting price from 2014 to 2024
- change_2021_2024_sell: average change rate in sale price from 2021 to 2024
- change_2021_2024_rent: average change rate in renting price from 2021 to 2024
- sell: sale prince: mean_meters * €/meter_sell
- rent: renting prince: mean_meters * €/meter_rent
- revaluation: how much does the apartment cost after the PER years have passed and applying the change_2021_2024_sell of price evolution.
- PER_adjusted: PER adjusted taking into account that the rent price will increase based on change_2021_2024_rent during the PER years.

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   distrito               256 non-null    object
 1   mean_meters            256 non-null    float64
 2   advertised_rent        256 non-null    float64
 3   advertised_sell        256 non-null    float64
 4   size_rent              256 non-null    float64
 5   size_sell              256 non-null    float64
 6   €/meter_rent           256 non-null    float64
 7   €/meter_sell           256 non-null    float64
 8   apartments             256 non-null    int64
 9   RB                     256 non-null    float64
 10  PER                    256 non-null    float64
 11  change_2014_2024_sell  256 non-null    float64
 12  change_2014_2024_rent  256 non-null    float64
 13  change_2021_2024_sell  256 non-null    float64
 14  change_2021_2024_rent  256 non-null    float64
 15  sell                   256 non-null    float64
 16  rent                   256 non-null    float64
 17  revaluation            256 non-null    float64
 18  PER_adjusted           256 non-null    float64
 19  norm_revaluation       256 non-null    float64
 20  norm_RB                256 non-null    float64
 21  inverse_PER            256 non-null    float64
 22  norm_PER               256 non-null    float64
dtypes: float64(21), int64(1), object(1)
memory usage: 46.1+ KB

## Input

In [3]:
input_money = input('Enter the money you want to invest:')

weight_revaluation = input('How many points do you give to revaluation?')
weight_rent_anual = input('How many points do you give to RB (Anual rental return)?')
weight_per = input('How many points do you give to PER?')

top = input('Number of columns you want to plot')

result = calculate_investment_score(data, input_money, weight_revaluation, weight_rent_anual, weight_per)
result.head(int(top))

,distrito,size_rent,size_sell,mean_meters,rent,sell,RB,PER,score,revaluation,loan,advertised_rent,advertised_sell
83,el-escorial,1.000,1.000,30.000,428.571,68571.429,7.500,13.333,0.446,1107483.550,18571.429,1.000,2.000
153,parla,0.000,1.000,30.000,0.000,72729.730,0.000,0.000,0.000,72729.730,22729.730,0.000,2.000
101,getafe,1.000,2.000,30.000,528.000,78025.210,8.120,12.315,0.482,687094.184,28025.210,1.533,1.510
0,alcala-de-henares,0.000,2.000,30.000,0.000,94928.571,0.000,0.000,0.000,94928.571,44928.571,0.000,1.217
168,puente-de-vallecas,15.000,59.000,30.000,992.682,98549.747,12.087,8.273,0.718,648693.863,48549.747,1.295,2.012
45,carabanchel,23.000,21.000,30.000,1141.744,102666.990,13.345,7.493,0.793,589407.856,52666.990,1.565,2.276
252,villaviciosa-de-odon,9.000,3.000,50.000,1167.130,104000.000,13.467,7.426,0.800,286837.525,54000.000,1.532,4.000
70,collado-villalba,2.000,2.000,30.000,628.378,113850.357,6.623,15.098,0.393,1761333.462,63850.357,1.417,1.033
10,alcorcon,0.000,2.000,30.000,0.000,115384.615,0.000,0.000,0.000,115384.615,65384.615,0.000,1.567
246,villaverde,8.000,2.000,30.000,825.626,120357.143,8.232,12.148,0.489,1221041.621,70357.143,1.443,1.500
247,villaverde,42.000,73.000,50.000,949.715,121636.791,9.369,10.673,0.557,931423.343,71636.791,1.499,1.829
154,parla,2.000,11.000,50.000,845.152,123583.408,8.206,12.186,0.488,812658.966,73583.408,1.022,2.113
5,alcobendas,10.000,3.000,30.000,1037.386,123994.253,10.040,9.960,0.596,443413.146,73994.253,1.149,4.318
124,leganes,3.000,5.000,30.000,787.406,124617.438,7.582,13.189,0.450,890135.251,74617.438,1.622,1.600
144,mostoles,2.000,2.000,30.000,765.000,129517.582,7.088,14.109,0.421,1484275.262,79517.582,1.267,1.683
119,latina,27.000,6.000,30.000,964.239,130987.010,8.834,11.320,0.525,1491935.387,80987.010,1.445,1.911
189,san-lorenzo-de-el-escorial,2.000,7.000,50.000,800.980,131172.421,7.328,13.647,0.435,1660539.882,81172.421,1.783,1.817
159,pinto,5.000,4.000,50.000,853.929,131947.552,7.766,12.877,0.461,390841.772,81947.552,1.553,4.150
16,aranjuez,10.000,18.000,50.000,681.704,133480.927,6.129,16.317,0.364,1619193.664,83480.927,1.130,1.597
145,mostoles,3.000,10.000,50.000,853.460,134713.719,7.602,13.154,0.452,1308889.701,84713.719,1.744,2.990
21,arganda,0.000,11.000,50.000,0.000,135927.956,0.000,0.000,0.000,135927.956,85927.956,0.000,1.324
88,fuencarral,10.000,3.000,30.000,812.281,140517.375,6.937,14.416,0.412,895979.433,90517.375,1.275,1.211
213,tres-cantos,3.000,1.000,50.000,998.062,142105.263,8.428,11.865,0.501,1261122.829,92105.263,1.811,10.000
102,getafe,11.000,23.000,50.000,976.753,142319.841,8.236,12.142,0.489,1215698.094,92319.841,1.204,2.975
223,valdemoro,5.000,6.000,50.000,677.370,142465.080,5.706,17.527,0.339,886246.177,92465.080,1.347,1.533
204,torrejon-de-ardoz,8.000,10.000,50.000,924.298,143399.435,7.735,12.929,0.459,953575.194,93399.435,1.390,1.611
217,usera,24.000,4.000,30.000,1191.374,143563.596,9.958,10.042,0.592,1511810.872,93563.596,1.607,2.008
65,ciudad-lineal,14.000,7.000,30.000,1076.760,144491.999,8.942,11.183,0.531,1744949.840,94491.999,1.241,2.310
232,villa-de-vallecas,190.000,7.000,30.000,1280.873,144582.143,10.631,9.406,0.632,768469.123,94582.143,1.282,1.462
183,san-blas,5.000,6.000,30.000,929.387,147251.261,7.574,13.203,0.450,1105873.507,97251.261,1.480,1.262
15,aranjuez,1.000,1.000,30.000,575.000,150000.000,4.600,21.739,0.273,4170008.460,100000.000,1.003,1.300
139,moratalaz,3.000,1.000,30.000,735.913,150000.000,5.887,16.986,0.350,4243356.479,100000.000,1.195,1.800
46,carabanchel,49.000,104.000,50.000,1226.772,150249.977,9.798,10.206,0.582,1623974.454,100249.977,1.370,1.775
84,el-escorial,1.000,1.000,50.000,937.500,152685.185,7.368,13.572,0.438,2591905.438,102685.185,2.000,2.000
11,alcorcon,3.000,13.000,50.000,979.195,153168.578,7.672,13.035,0.456,1123491.971,103168.578,1.241,1.656
93,fuenlabrada,1.000,13.000,50.000,732.759,153346.771,5.734,17.439,0.341,1444701.689,103346.771,1.300,1.807
79,coslada,2.000,11.000,50.000,997.294,153671.525,7.788,12.841,0.463,1287486.005,103671.525,1.033,2.209
114,las-rozas-de-madrid,2.000,4.000,30.000,701.923,153711.982,5.480,18.249,0.326,4656903.645,103711.982,1.267,2.433
97,galapagar,3.000,4.000,50.000,856.552,154383.327,6.658,15.020,0.396,2419178.565,104383.327,1.522,2.467
233,villa-de-vallecas,24.000,44.000,50.000,1128.621,156448.270,8.657,11.552,0.514,1217115.372,106448.270,1.269,2.122
155,parla,14.000,112.000,80.000,1065.317,156489.141,8.169,12.241,0.485,1037933.885,106489.141,1.381,2.052
129,majadahonda,1.000,1.000,30.000,975.000,156666.667,7.468,13.390,0.444,640555.484,106666.667,1.019,1.033
169,puente-de-vallecas,43.000,158.000,50.000,1014.364,157235.191,7.742,12.917,0.460,2981015.334,107235.191,1.303,2.399
75,colmenar-viejo,0.000,5.000,50.000,0.000,161620.590,0.000,0.000,0.000,161620.590,111620.590,0.000,2.033
17,aranjuez,10.000,45.000,80.000,991.420,163426.095,7.280,13.737,0.432,1335969.727,113426.095,1.357,2.136
120,latina,31.000,28.000,50.000,1164.754,164450.313,8.499,11.766,0.505,2061191.824,114450.313,1.304,2.134
125,leganes,5.000,29.000,50.000,958.662,164685.014,6.985,14.316,0.415,1391527.580,114685.014,1.187,1.929
218,usera,29.000,65.000,50.000,1295.421,166609.798,9.330,10.718,0.554,2055807.369,116609.798,1.467,2.196
198,tetuan,79.000,56.000,30.000,1160.990,167716.570,8.307,12.038,0.494,2227797.425,117716.570,1.438,1.975
140,moratalaz,0.000,15.000,50.000,0.000,168205.039,0.000,0.000,0.000,168205.039,118205.039,0.000,1.876